# Generated by Django 6.0.3 on 2026-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="midiacondominio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("condominio", "Condomínio Atual"),
                    ("projetos_futuros", "Projetos Futuros"),
                ],
                default="condominio",
                max_length=20,
            ),
        ),
    ]
