# Generated by Django 6.0.3 on 2026-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_midiacondominio_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("morador", "Morador"),
                    ("proprietario", "Proprietário"),
                    ("moderador", "Moderador"),
                    ("admin", "Administrador"),
                ],
                default="morador",
                max_length=20,
            ),
        ),
    ]
