# Generated by Django 6.0.4 on 2026-05-18 22:37
# NOTA: esta migration ja foi aplicada no banco em 2026-04-08 com o conteudo
# abaixo (Propaganda + campos do Usuario). O arquivo nao havia sido commitado
# no git, mas o estado do banco corresponde a estas operacoes. Mantido aqui
# para que o historico de migrations bata com a realidade do banco.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_visitasite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ex: @suaempresa', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ramo_atividade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ramo de Atividade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('morador', 'Morador'), ('proprietario', 'Proprietário'), ('moderador', 'Moderador'), ('admin', 'Administrador'), ('empresa', 'Empresa'), ('fornecedor', 'Fornecedor')], default='morador', max_length=20),
        ),
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='propagandas/', verbose_name='Imagem do Anúncio')),
                ('instagram', models.CharField(blank=True, help_text='Ex: https://instagram.com/suaempresa', max_length=300, verbose_name='Link do Instagram')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Veiculação')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Veiculação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagandas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propaganda',
                'verbose_name_plural': 'Propagandas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
