# Generated by Django 6.0.4 on 2026-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_suspensaomorador'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensaomorador',
            name='bloqueia_classificados',
            field=models.BooleanField(default=False, verbose_name='Bloquear classificados'),
        ),
        migrations.AddField(
            model_name='suspensaomorador',
            name='bloqueia_galeria',
            field=models.BooleanField(default=False, verbose_name='Bloquear upload galeria'),
        ),
        migrations.AddField(
            model_name='suspensaomorador',
            name='bloqueia_mural',
            field=models.BooleanField(default=False, verbose_name='Bloquear mural/comunidade'),
        ),
        migrations.AddField(
            model_name='suspensaomorador',
            name='bloqueia_propagandas',
            field=models.BooleanField(default=False, verbose_name='Bloquear propagandas'),
        ),
        migrations.AddField(
            model_name='suspensaomorador',
            name='bloqueia_reservas',
            field=models.BooleanField(default=True, verbose_name='Bloquear reservas'),
        ),
    ]
