# Generated by Django 6.1 on 2026-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_suspensaomorador_bloqueia_classificados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('morador', 'Morador'), ('proprietario', 'Proprietário'), ('moderador', 'Moderador'), ('admin', 'Administrador'), ('portaria', 'Portaria'), ('empresa', 'Empresa'), ('fornecedor', 'Fornecedor')], default='morador', max_length=20),
        ),
    ]
