# Generated by Django 6.1.1 on 2026-09-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Liberado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Moderador ou administrador que liberou este cadastro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por'),
        ),
    ]
