# Generated by Django 6.1.1 on 2026-09-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_aprovado_em_usuario_aprovado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroModeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('cadastro_aprovado', 'Cadastro aprovado'), ('cadastro_rejeitado', 'Cadastro rejeitado'), ('cadastro_criado', 'Cadastro criado'), ('cadastro_editado', 'Cadastro alterado'), ('senha_redefinida', 'Senha redefinida'), ('suspensao_aplicada', 'Suspensao aplicada'), ('suspensao_removida', 'Suspensao removida'), ('promovido_moderador', 'Promovido a moderador'), ('rebaixado_morador', 'Rebaixado para morador'), ('limite_definido', 'Limite de reservas definido'), ('limite_removido', 'Limite de reservas removido'), ('reserva_cancelada', 'Reserva cancelada'), ('bloqueio_criado', 'Bloqueio de espaco criado'), ('bloqueio_removido', 'Bloqueio de espaco removido'), ('midia_enviada', 'Fotos/videos enviados'), ('midia_excluida', 'Midia excluida'), ('conteudo_aprovado', 'Conteudo aprovado'), ('conteudo_rejeitado', 'Conteudo rejeitado'), ('conteudo_excluido', 'Conteudo excluido')], max_length=40, verbose_name='Acao')),
                ('moderador_nome', models.CharField(blank=True, max_length=120)),
                ('alvo_nome', models.CharField(blank=True, max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alvo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_moderacao', to=settings.AUTH_USER_MODEL, verbose_name='Sobre quem')),
                ('moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_moderacao', to=settings.AUTH_USER_MODEL, verbose_name='Quem fez')),
            ],
            options={
                'verbose_name': 'Registro de moderacao',
                'verbose_name_plural': 'Historico da moderacao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['alvo_usuario', '-criado_em'], name='core_regist_alvo_us_e5c63a_idx'), models.Index(fields=['moderador', '-criado_em'], name='core_regist_moderad_3a3176_idx')],
            },
        ),
    ]
