# Generated by Django 6.1.1 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registromoderacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromoderacao',
            name='acao',
            field=models.CharField(choices=[('cadastro_aprovado', 'Cadastro aprovado'), ('cadastro_rejeitado', 'Cadastro rejeitado'), ('cadastro_criado', 'Cadastro criado'), ('cadastro_editado', 'Cadastro alterado'), ('senha_redefinida', 'Senha redefinida'), ('suspensao_aplicada', 'Suspensao aplicada'), ('suspensao_removida', 'Suspensao removida'), ('promovido_moderador', 'Promovido a moderador'), ('rebaixado_morador', 'Rebaixado para morador'), ('limite_definido', 'Limite de reservas definido'), ('limite_removido', 'Limite de reservas removido'), ('reserva_cancelada', 'Reserva cancelada'), ('bloqueio_criado', 'Bloqueio de espaco criado'), ('bloqueio_removido', 'Bloqueio de espaco removido'), ('midia_enviada', 'Fotos/videos enviados'), ('midia_excluida', 'Midia excluida'), ('conteudo_aprovado', 'Conteudo aprovado'), ('conteudo_rejeitado', 'Conteudo rejeitado'), ('conteudo_excluido', 'Conteudo excluido'), ('lista_exportada', 'Lista de moradores exportada')], max_length=40, verbose_name='Acao'),
        ),
    ]
