# Generated by Django 6.0.3 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("venda", "Venda"), ("aluguel", "Aluguel")],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bloco", models.CharField(max_length=10, verbose_name="Bloco")),
                (
                    "apartamento",
                    models.CharField(max_length=10, verbose_name="Apartamento"),
                ),
                ("quartos", models.IntegerField(default=2, verbose_name="Quartos")),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Área (m²)",
                    ),
                ),
                (
                    "mobiliado",
                    models.BooleanField(default=False, verbose_name="Mobiliado"),
                ),
                (
                    "aceita_pet",
                    models.BooleanField(default=False, verbose_name="Aceita Pet"),
                ),
                (
                    "garagem",
                    models.IntegerField(default=1, verbose_name="Vagas Garagem"),
                ),
                (
                    "contato_telefone",
                    models.CharField(max_length=20, verbose_name="Telefone de Contato"),
                ),
                (
                    "contato_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail de Contato"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("vendido", "Vendido/Alugado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("destaque", models.BooleanField(default=False)),
                ("visualizacoes", models.IntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
                "ordering": ["-destaque", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="FotoAnuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="anuncios/")),
                ("principal", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Foto do Anúncio",
                "verbose_name_plural": "Fotos do Anúncio",
                "ordering": ["-principal", "ordem"],
            },
        ),
    ]
