# Generated by Django 6.0.3 on 2026-03-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classificados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncio",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anuncios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fotoanuncio",
            name="anuncio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotos",
                to="classificados.anuncio",
            ),
        ),
    ]
