# Generated by Django 6.0.3 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="MensagemAdministracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nova", "Nova"),
                            ("lida", "Lida"),
                            ("respondida", "Respondida"),
                        ],
                        default="nova",
                        max_length=15,
                    ),
                ),
                ("resposta", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mensagem à Administração",
                "verbose_name_plural": "Mensagens à Administração",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="MuralPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("evento", "Evento"),
                            ("aviso", "Aviso"),
                            ("sugestao", "Sugestão"),
                            ("achados", "Achados e Perdidos"),
                        ],
                        default="geral",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="mural/"),
                ),
                ("aprovado", models.BooleanField(default=False)),
                ("fixado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Post do Mural",
                "verbose_name_plural": "Posts do Mural",
                "ordering": ["-fixado", "-criado_em"],
            },
        ),
    ]
