# Generated by Django 6.0.4 on 2026-05-18 22:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador da URL, ex: quadra-beach-tennis', unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reservas/espacos/', verbose_name='Foto')),
                ('horario_abertura', models.TimeField(default=datetime.time(6, 0), verbose_name='Horario de abertura')),
                ('horario_fechamento', models.TimeField(default=datetime.time(22, 0), verbose_name='Horario de fechamento')),
                ('duracao_slot_min', models.PositiveIntegerField(default=60, help_text='Tempo de cada reserva em minutos. Ex: 60 = 1 hora.', verbose_name='Duracao de cada slot (minutos)')),
                ('max_reservas_futuras_por_usuario', models.PositiveIntegerField(default=3, verbose_name='Maximo de reservas futuras por usuario')),
                ('antecedencia_min_horas', models.PositiveIntegerField(default=1, verbose_name='Antecedencia minima para reservar (horas)')),
                ('antecedencia_max_dias', models.PositiveIntegerField(default=7, verbose_name='Antecedencia maxima para reservar (dias)')),
                ('cancelamento_min_horas', models.PositiveIntegerField(default=2, verbose_name='Cancelar ate quantas horas antes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espaco',
                'verbose_name_plural': 'Espacos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Inicio')),
                ('data_fim', models.DateTimeField(verbose_name='Fim')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_criados', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='reservas.espaco')),
            ],
            options={
                'verbose_name': 'Bloqueio de espaco',
                'verbose_name_plural': 'Bloqueios de espacos',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['espaco', 'data_inicio', 'data_fim'], name='reservas_bl_espaco__7f6277_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('convidados', models.TextField(blank=True, help_text='Nomes dos convidados (um por linha), se houver.', verbose_name='Convidados')),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.espaco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data', '-hora_inicio'],
                'indexes': [models.Index(fields=['espaco', 'data'], name='reservas_re_espaco__dc6f82_idx'), models.Index(fields=['usuario', 'status'], name='reservas_re_usuario_0607ac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmada')), fields=('espaco', 'data', 'hora_inicio'), name='unique_reserva_confirmada_por_slot')],
            },
        ),
    ]
