# Generated by Django 6.0.4 on 2026-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='max_reservas_por_dia_por_usuario',
            field=models.PositiveIntegerField(default=1, help_text='Quantas reservas o mesmo morador pode ter em um unico dia. Padrao: 1.', verbose_name='Maximo de reservas no mesmo dia por usuario'),
        ),
    ]
