# Generated by Django 6.1 on 2026-08-29 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_espaco_max_reservas_por_dia_por_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='max_reservas_por_semana_por_usuario',
            field=models.PositiveIntegerField(default=2, help_text='Quantas reservas o mesmo morador pode fazer por semana (segunda a domingo). Padrao: 2. Pode ser ajustado individualmente em Moderacao > Limite de reservas.', verbose_name='Maximo de reservas por semana por usuario'),
        ),
        migrations.CreateModel(
            name='LimiteReservaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_por_semana', models.PositiveIntegerField(help_text='Quantas reservas por semana (segunda a domingo) este morador pode fazer. 0 = nenhuma.', verbose_name='Maximo de reservas por semana')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('definido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_reserva_definidos', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_usuarios', to='reservas.espaco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limite de reservas do morador',
                'verbose_name_plural': 'Limites de reservas dos moradores',
                'ordering': ['usuario__bloco', 'usuario__apartamento'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'espaco'), name='unique_limite_por_usuario_espaco')],
            },
        ),
    ]
