# Generated by Django 6.1 on 2026-08-29 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_espaco_max_reservas_por_semana_por_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirado_por', models.CharField(max_length=120, verbose_name='Retirado por')),
                ('retirado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Retirado em')),
                ('raquetes', models.PositiveSmallIntegerField(default=2, verbose_name='Raquetes')),
                ('bolinhas', models.PositiveSmallIntegerField(default=3, verbose_name='Bolinhas')),
                ('devolvido_por', models.CharField(blank=True, max_length=120, verbose_name='Devolvido por')),
                ('devolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Devolvido em')),
                ('observacao', models.TextField(blank=True, help_text='Alguma avaria, item faltando ou aviso sobre a devolucao.', verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('devolucao_registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_recebidos', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='reservas.reserva')),
                ('retirada_registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_entregues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kit de jogo',
                'verbose_name_plural': 'Kits de jogo',
                'ordering': ['-retirado_em'],
                'indexes': [models.Index(fields=['devolvido_em'], name='reservas_ki_devolvi_78018b_idx')],
            },
        ),
    ]
