# Generated by Django 6.1 on 2026-08-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_kitjogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, help_text='Opcional, mas agiliza a liberacao na portaria.', max_length=14, verbose_name='CPF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados_lista', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['reserva'], name='reservas_co_reserva_c9ecf9_idx')],
            },
        ),
    ]
