# Generated by Django 6.1 on 2026-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_migrar_convidados_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='cpf',
            field=models.CharField(help_text='Obrigatorio para novos convidados: e o que a portaria confere na entrada.', max_length=14, verbose_name='CPF'),
        ),
    ]
