# Generated by Django 6.1 on 2026-08-29 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_convidado_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitjogo',
            name='entregue_por_vigia',
            field=models.CharField(blank=True, help_text='Nome de quem estava no plantao e entregou o kit.', max_length=120, verbose_name='Vigilante que entregou'),
        ),
        migrations.AddField(
            model_name='kitjogo',
            name='recebido_por_vigia',
            field=models.CharField(blank=True, help_text='Nome de quem estava no plantao e recebeu o kit de volta.', max_length=120, verbose_name='Vigilante que recebeu'),
        ),
        migrations.AlterField(
            model_name='kitjogo',
            name='devolucao_registrada_por',
            field=models.ForeignKey(blank=True, help_text='Conta usada para registrar (a portaria pode ser compartilhada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitjogo',
            name='retirada_registrada_por',
            field=models.ForeignKey(blank=True, help_text='Conta usada para registrar (a portaria pode ser compartilhada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_entregues', to=settings.AUTH_USER_MODEL),
        ),
    ]
